server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: citystream-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.citystream: INFO
    com.amazonaws: WARN