spring:
  application:
    name: citystream-producer

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}  # Changed for Docker internal listener
  topic:
    city-events: city-events

server:
  port: 8080  # Changed from 8081 to avoid conflict

logging:
  level:
    com.citystream.producer: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
  
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  metrics:
    export:
      prometheus:
        enabled: true